version: "3.9"
name: "book-store-spring-boot-microservices"
services:
  catalogue-service:
    image: niladrdev/bookstore-catalogue-service
    container_name: catalogue-service
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      catalogue-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://catalogue-db:5432/catalogue_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_ENABLED: "true"
    networks:
      - book-store-network
    deploy:
      resources:
        limits:
          memory: 800m
networks:
  book-store-network:
    driver: bridge