version: "3.8"
name: "book-store-spring-boot-microservices"
services:
  catalogue-db:
    image: postgres:18
    container_name: catalogue-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogue_db
    ports:
      - "1000:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - catalogue-db-data:/var/lib/postgresql
    networks:
      - book-store-network
volumes:
  catalogue-db-data:
networks:
  book-store-network:
    driver: bridge