name: Catalogue Service CI/CD Pipeline

on:
  push:
    paths:
      - 'catalogue-service/**'
    branches:
      - 'main'
    pull_request:
      branches: [ main ]
jobs:
  build:
    name: Build and Test Catalogue Service
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalogue-service
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-catalogue-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x mvnw

      - name: Build with maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          echo "Docker Image built and pushed successfully."
          docker push $DOCKER_IMAGE_NAME